### ISSUE TITLE
sphinx-testing vs. sphinx.testing

### ISSUE THREAD

**Issue by jnikula** [sphinx-doc/sphinx-testing#11]
Which should I use for testing extensions going forward? I've been using sphinx-testing (this project) until now, but only recently stumbled upon https://github.com/sphinx-doc/sphinx/issues/3458. Is sphinx-testing deprecated?

The sphinx documentation about writing extensions says nothing about testing.

**Comment by tk0miya** [comment]
Both `sphinx-testing` (this package) and `sphinx.testing` are alive. The first one is based on nosetest framework, and other is based on pytest. You can choose either one you like.

**Comment by jnikula** [comment]
Thanks for confirming I don't have to worry about migrating away from `sphinx-testing` for now.
