### ISSUE TITLE
@with_app decorator should return the value of the decorated function

### ISSUE THREAD

**Issue by jnikula** [sphinx-doc/sphinx-testing#12]
Seems to me you can't use `@with_app` to decorate a function that should return a value, because the decorator doesn't return the value of the `func` passed in. A simple test seems to confirm this.

https://github.com/sphinx-doc/sphinx-testing/blob/master/src/sphinx_testing/util.py#L162

**Comment by tk0miya** [comment]
+1; Reasonable.
Could you send us a pull request please?
