### ISSUE TITLE
replacing nose and nose-cov dependencies

### ISSUE THREAD

**Issue by alfredodeza** [sphinx-doc/sphinx-testing#15]
I am currently working on packaging sphinx-testing for CentOS8 and we have issues because nose-cov is not available.

The `nose` package is currently unmaintained (and has been for a while) and the `nose-cov` package hasn't received changes since 2012.

I was able to run tests and check coverage using `pytest`. Would you be willing to accept a PR that introduces these changes?

**Comment by tk0miya** [comment]
Thank you for proposal. But we have another implementation for pytest as `sphinx.testing` now. And it is now bundled in Sphinx package. So only we can do is deprecating this package.

**Comment by alfredodeza** [comment]
hey @tk0miya thank you for your feedback. I understand that `sphinx.testing` is a thing now, but in CentOS8 and other distros, there are many packages that depend on older versions of Sphinx.  

In this particular case, it is `python-sphinx-removed-in` that requires this package. 

I do understand being hesitant to take the proposed changes in, but would you be willing to accept the idea of verifying this package with `pytest` vs. `nose` ? We can do that on our end, and you can see that the tests do pass. If that works for you, then I would link this ticket in the spec file needed to build this package as a reason on using pytest

**Comment by torfsen** [comment]
@tk0miya: It would be great if `sphinx.testing` was mentioned in this project's README. Googling for a way to test my Sphinx extension led me here, and without your comment I wouldn't have known about `sphinx.testing` at all.

**Comment by tk0miya** [comment]
I still don't understand switching test runner of this package to pytest helps CentOS8. Why is this needed? This package does not depend on node itself directly. So such change does not help CentOS8 to me, right?

**Comment by tk0miya** [comment]
@torfsen Good point, I added deprecation message and a hyperlink to README (see #17)

**Comment by alfredodeza** [comment]
> I still don't understand switching test runner of this package to pytest helps CentOS8. Why is this needed? 

Because nose-cov is not packaged (unavailable), and it is a test dependency that is required to package this project. The last update in the nose-cov project was six years ago.

> This package does not depend on node itself directly. So such change does not help CentOS8 to me, right?

In packaging there are "build" requirements and runtime requirements. This package doesn't require nose or nose-cov as a runtime dependency, but it does declare them for testing, making it a "build" requirement. 

In RPM packaging, a `check` section is present that runs a verification of the package. The guidance for this section is that it uses what the project defines as needed to run it. In the case of sphinx-testing it is nose and nose-cov.

A simple acknowledgement by you that using `pytest` instead of `nose` (and `nose-cov`) would suffice to run this check means that I can get the changes needed in packaging without anything touching this repository.

Alternatively, if you want to merge the proposed changes, that would work as well. Thank you for your help!

**Comment by tk0miya** [comment]
>Because nose-cov is not packaged (unavailable), and it is a test dependency that is required to package this project. The last update in the nose-cov project was six years ago.

Who requires nose-cov? IMO, sphinx-testing does not depend on it.


If you meant, the changing to pytest is needed for CentOS8 packaging. I think you should patch to sphinx-testing on packaging. AFAIK, many users of this package has used nose for their test runner. So we should not move to pytest only for packaging reason.

**Comment by alfredodeza** [comment]
> Who requires nose-cov? IMO, sphinx-testing does not depend on it.

@tk0miya you are right that sphinx-testing does not depend on it. What I mean is that sphinx-testing requires it for *testing*. You can see that is defined here: https://github.com/sphinx-doc/sphinx-testing/blob/master/tox.ini#L5-L6

> 
> If you meant, the changing to pytest is needed for CentOS8 packaging. I think you should patch to sphinx-testing on packaging. AFAIK, many users of this package has used nose for their test runner. So we should not move to pytest only for packaging reason.

Well, that is what I am asking. There is no need to patch, what I need to know is:

a) Are you OK with merging the PR to use pytest? (seems like the answer is NO here)
b) Are you OK with *packaging* using pytest to verify these tests instead of nose?

**Comment by tk0miya** [comment]
>you are right that sphinx-testing does not depend on it. What I mean is that sphinx-testing requires it for testing. You can see that is defined here: https://github.com/sphinx-doc/sphinx-testing/blob/master/tox.ini#L5-L6

I'm confusing. Only I can see in tox.ini is "nose", not "nose-cov". Do you mean "nose" is not packaged?

>a) Are you OK with merging the PR to use pytest? (seems like the answer is NO here)
>b) Are you OK with packaging using pytest to verify these tests instead of nose?

a) No and b) Yes. If my understanding correct, moving to pytest is needed for packaging reason now. I think that is not enough to change it in upstream.

Historically, this package has been made for mainly nosetests. And many users of this library have used also it. Therefore I'd not like to move to pytest. Of course, I know changing it does not mean to move users' to pytest too. But I worry about the moving will cause meaningless confuse to users.

**Comment by alfredodeza** [comment]
Thank you for helping out. Being able to verify tests on our end with what we have is good enough. I'll close this issue and the corresponding PR, and will link to these in our end in the packaging files.
