### ISSUE TITLE
Proposal: archive sphinx-testing project

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx-testing#22]
Since 1.6, we migrated to pytest and integarted the testing package to sphinx-core as sphinx.testing. As a result, this package is no longer maintained. Additionally, nose project has also been not maintained now (the latest release is in 5 years ago!). So it's time to say this project not maintained now.

@shimizukawa Do you have any comment?

**Comment by shimizukawa** [comment]
+1 to archive. Good bye python2!

**Comment by tk0miya** [comment]
After a while, nobody responds to our call for maintainers. So I'm going to archive this.
